server:
  port: 6662

spring:
  application:
#    服务器id
    name: ms-control-center
#    从本地获取配置
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:ms-control-center/config
#          防止config拦截eureka请求，最好给每个功能分配自己的前缀
        prefix: /config

eureka:
  instance:
#    每隔一定时间发送一次心跳
    lease-renewal-interval-in-seconds: 3
#    告知服务端一定时间还未收到心跳，就移除该服务
    lease-expiration-duration-in-seconds: 5
  client:
#    注册地址
    service-url:
      defaultZone: http://localhost:6662/eureka
#    开启健康检测
    healthcheck:
      enabled: true
#      客户端获取eureka中注册应用列表的时长
    registry-fetch-interval-seconds: 5
  server:
#    注册中心清理过期服务间隔
    eviction-interval-timer-in-ms: 10000
#    禁用第二级缓存，提高应用更新速度
    use-read-only-response-cache: false
